/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConsoleWindow.java
 *
 * Created on 24-mar-2011, 22.47.39
 */

package com.oryzone.mvdetector.gui;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultListModel;

/**
 *
 * @author Luciano
 */
public class ConsoleWindow extends javax.swing.JFrame {

    protected DefaultListModel data;
    

    /** Creates new form ConsoleWindow */
    public ConsoleWindow(){
        initComponents();
        data = new DefaultListModel();
        this.list.setModel(data);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList();

        setTitle("Console");
        setPreferredSize(new java.awt.Dimension(620, 280));
        setSize(new java.awt.Dimension(600, 280));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(null);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        list.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(list);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList list;
    // End of variables declaration//GEN-END:variables


    /**
     * Adds a new entry message on the top of the console
     * @param message the message to add
     * @return the same instance of the console (for method chaining)
     */
    public ConsoleWindow log(String message)
    {
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        Date date = new Date();
        data.add(0, dateFormat.format(date) + " - " + message);
        return this;
    }


    /**
     * Clears the console.
     * @return the same instance of the console (for method chaining)
     */
    public ConsoleWindow clear()
    {
        data.clear();
        return this;
    }


    /**
     * Toggle the visibility of the console
     * @return the same instance of the console (for method chaining)
     */
    public ConsoleWindow toggle()
    {
        this.setVisible(!this.isVisible());
        return this;
    }



}
